### ISSUE TITLE
ModelBuilder Implementations

### ISSUE THREAD

**Issue by iamjonco** [epsilonlabs/epsilon-sigma-executors#2]
Concrete implementations of `ModelBuilder` and `CachedModelBuilder` are missing from the API

**Comment by arcanefoam** [comment]
Initially, we decided to provide builders as separate plugins so they could be installed independently. Not sure that makes sense in this kind of distribution. We could ship the ones we have and then add more as needed. It will also provide ideas for people implementing their own.

**Comment by iamjonco** [comment]
One option is to refactor the current code base into a multi module project to keep the executors and builders separate and produce two separate artifacts for deployment. Users only interested in developing a new builder could then only depend on the ModelBuilder API. 

That brings up the question of whether to then move the builder module out into a separate repo in entirely.

**Comment by arcanefoam** [comment]
Separating the model builder completely makes sense as the executor API is completly independent, and then having a multi module project for the builders makes sense to.
I will create a new repo and make the changes to separate the code.
